FPH_Admin_View_Business Resolved
ctc-uci/fph-frontend pull request #23
Opened 2024-01-31 01:38 UTC by ShawnnnLiu

Issue #21 resolved

2024-01-31 01:39 UTC, ctc-devops commented on src/components/ViewBusiness/ViewBusiness.jsx
> +  }, [id]);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'fetchBusiness'. Either include it or remove the dependency array.

2024-02-02 21:23 UTC, srukelman requested changes
Good work jits. CSS looks good. I didn't see functionality for the edit and delete. Josh says if you don't get it done you're cut.

2024-02-02 21:23 UTC, srukelman commented on src/components/BusinessTable/BusinessTable.jsx
> +      console.log(response.data);
console.log isn't necessary

2024-02-02 21:23 UTC, srukelman commented on src/components/BusinessTable/BusinessTable.jsx
> +  const handleRowClick = async id => {
nit: id should be parenthesized here

2024-02-02 21:23 UTC, srukelman commented on src/components/ViewBusiness/ViewBusiness.jsx
> +      console.log(`Fetching business details for ID: ${id}`);
console.logs aren't necessary

2024-02-02 21:23 UTC, srukelman commented on src/components/ViewBusiness/ViewBusiness.jsx
> +      console.log('Response received:', response);
console.log

2024-02-02 21:23 UTC, srukelman commented on src/components/ViewBusiness/ViewBusiness.jsx
> +  // }
You can get rid of this, unless there's a reason it needs to be there.

2024-02-02 21:23 UTC, srukelman commented on src/components/ViewBusiness/ViewBusiness.jsx
> +  return (
in the future try to break down the jsx blocks into smaller functions that return jsx for readability

2024-02-02 21:23 UTC, srukelman commented on yarn.lock
don't need to include yarn.lock in your commit

2024-02-02 21:23 UTC, srukelman commented on src/components/ViewBusiness/ViewBusiness.jsx
> +                    1/12/2024
you can get the actual dates if you run a GET by business_id on the donation router and use the timestamps on each of those and display them here

2024-02-07 05:33 UTC, merged