Business Donation History Resolved
ctc-uci/fph-frontend pull request #36
Opened 2024-02-12 05:07 UTC by benson-fm

resolves #33

2024-02-17 05:42 UTC, srukelman requested changes
good job jits. y'all cooked. pretty minor changes. try to get them done by monday so we can merge. 😗

2024-02-17 05:42 UTC, srukelman commented on src/components/BusinessDonationHistory/BusinessDonationHistory.jsx
> +              <Td>{item.date}</Td>
iterate through the columns rather than explicitly accessing each column. see BusinessTable for an example.

2024-02-17 05:42 UTC, srukelman commented on src/components/BusinessDonationHistory/BusinessDonationHistory.jsx
> +  const TABLE_HEADERS = ['reporter', 'food_bank_donation', 'date', 'action'];
nit: format cleanly since these are the values that appear to the user

2024-02-17 05:42 UTC, srukelman commented on src/components/BusinessDonationHistory/ViewDonationHistory/ViewDonationHistory.jsx
> +  // }
delete commented code if you're not using it

2024-02-17 05:42 UTC, srukelman commented on src/components/BusinessDonationHistory/ViewDonationHistory/ViewDonationHistory.jsx
> +      console.log('Response received:', response);
remove unnecessary console.logs

2024-02-17 05:42 UTC, srukelman commented on src/components/BusinessDonationHistory/BusinessDonationHistory.jsx
> +      console.log(response.data);
remove unnecessary console.log

2024-02-20 01:10 UTC, ctc-devops commented on src/components/BusinessDonationHistory/BusinessDonationHistory.jsx
> +  }, []);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'backend'. Either include it or remove the dependency array.

2024-02-20 01:10 UTC, ctc-devops commented on src/components/BusinessDonationHistory/ViewDonationHistory/ViewDonationHistory.jsx
> +  }, [id]);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has a missing dependency: 'fetchDonation'. Either include it or remove the dependency array.

2024-02-20 01:11 UTC, merged