Filter buttons admin dashboard
ctc-uci/fph-frontend pull request #39
Opened 2024-02-16 23:22 UTC by kaitlinnleung

closes #31

2024-02-16 23:23 UTC, ctc-devops commented on src/components/AdminFilterBusinesses/AdminFilterBusinesses.jsx
> +  }, [currentTab, currentPageNum]);
⚠️ **[eslint]** <[react-hooks/exhaustive-deps](https://github.com/facebook/react/issues/14920)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>React Hook useEffect has missing dependencies: 'businessDictionary' and 'loadInfo'. Either include them or remove the dependency array.

2024-02-17 21:05 UTC, Xire7 requested changes
very good stuff jits, just a lot of cleaning up uncommented code 👍

2024-02-17 21:05 UTC, Xire7 commented on src/App.jsx
> +      /> */}
If this was commented out to test code, remember to uncomment it out when merging for development.

2024-02-17 21:05 UTC, Xire7 commented on src/components/AdminFilterBusinesses/AdminFilterBusinesses.jsx
> +    //loadInfo(tab);
remove commented out unused code

2024-02-17 21:05 UTC, Xire7 commented on src/components/AdminFilterBusinesses/AdminFilterBusinesses.jsx
> +    // setBusinessDictionary(businessResponse.data);
delete unused code 👍

2024-02-17 21:05 UTC, Xire7 commented on src/components/BusinessTable/BusinessTable.jsx
> +        //setData(response.data);
delete commented code

2024-02-17 21:05 UTC, Xire7 commented on src/components/AdminDashboard/AdminDashboard.jsx
> +//import { ChevronRightIcon, ChevronLeftIcon } from '@chakra-ui/icons';
delete comment

2024-02-17 21:05 UTC, Xire7 commented on src/components/AdminFilterBusinesses/AdminFilterBusinesses.jsx
> +  const [currentTab, setCurrentTab] = useState('Active'); //change to all once all page is implemented
good comment, just need to backtrack to changing the state to all when that page is implemented

2024-02-21 03:57 UTC, merged