Business onboarding form break it up full css
ctc-uci/fph-frontend pull request #50
Opened 2024-03-01 16:08 UTC by KainoaNishida

jits this is full functioanlity done except for a link on the last page to go back to website.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                  webpage. I acknowledge that all information regarding Pets of the Homeless'
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                  By checking the "I Accept the Terms and Conditions" box and clicking the "Submit"
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                  By checking the "I Accept the Terms and Conditions" box and clicking the "Submit"
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                  By checking the "I Accept the Terms and Conditions" box and clicking the "Submit"
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                  By checking the "I Accept the Terms and Conditions" box and clicking the "Submit"
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-01 16:09 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                      <AlertTitle>You haven't accepted the Terms and Conditions</AlertTitle>
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.

2024-03-02 06:28 UTC, Madhu2244 requested changes
jits the submission does not work. in addition when you press the back button, all the form data is lost. dont create these states inside `FirstForm` `SecondForm` `ThirdForm` `FourthForm`, use the states from `formData` in here as the values to show to the user, such that when we press the back button, we don't lose all of our entries.

make sure the submission button works when you reraise the pr

2024-03-02 06:28 UTC, Madhu2244 commented on src/components/OnBoarding/FirstForm.jsx
> +            <Input marginTop='1vh'
`yarn format`, not gonna repeat comments you get the idea

2024-03-02 06:28 UTC, Madhu2244 commented on src/components/OnBoarding/FirstForm.jsx
> +  const [website, changeWebsite] = useState('');
dont create these states, use the states from `formData` in here, such that when we press the back button, we don't lose all of our entries

2024-03-02 06:28 UTC, Madhu2244 commented on src/components/OnBoarding/SecondForm.jsx
> +  const [country, changeCountry] = useState('');
dont create these states, use the states from `formData` in here, such that when we press the back button, we don't lose all of our entries

2024-03-02 06:28 UTC, Madhu2244 commented on src/components/OnBoarding/ThirdForm.jsx
> +  console.log(submitAndAcceptedFalse);
dont create these states, use the states from `formData` in here, such that when we press the back button, we don't lose all of our entries

2024-03-02 06:28 UTC, Madhu2244 commented on src/components/OnBoarding/ThirdForm.jsx
> +  );
dont create these states, use the states from `formData` in here, such that when we press the back button, we don't lose all of our entries

2024-03-02 10:11 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                    Homeless' operations, procedures, contacts, volunteers, recipients and donors is
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.

2024-03-02 10:11 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                    By checking the "I Accept the Terms and Conditions" box and clicking the
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-02 10:11 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                    By checking the "I Accept the Terms and Conditions" box and clicking the
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-02 10:11 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                    "Submit" button on this page, you acknowledge you have read and agree to the
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-02 10:11 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                    "Submit" button on this page, you acknowledge you have read and agree to the
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`"` can be escaped with `&quot;`, `&ldquo;`, `&#34;`, `&rdquo;`.

2024-03-02 17:47 UTC, ctc-devops commented on src/components/OnBoarding/ThirdForm.jsx
> +                              <AlertTitle>You haven't accepted the Terms and Conditions</AlertTitle>
🚫 **[eslint]** <[react/no-unescaped-entities](https://github.com/jsx-eslint/eslint-plugin-react/tree/master/docs/rules/no-unescaped-entities.md)> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`'` can be escaped with `&apos;`, `&lsquo;`, `&#39;`, `&rsquo;`.

2024-03-03 01:04 UTC, closed without merging